
# WorldCapitolsTriviaDict\
ArrayOfDictionaries = [{
        # Ancient Egypt Trivia
        'A Pharaoh never let his ______ be seen.': 'Hair',
        'Because they believed in ________, ancient Egyptians mummified bodies.': 'the afterlife',
        'How many pyramids have been discovered in Egypt so far?': 'Over 130',
        'Roughly how many different deities did the Ancient Egyptians believe in?': 'More than 2,000',
        'The Ancient Egyptians were the first civilization to invent __________.': 'Writing',
        'The Egyptian alphabet consisted of more than ______ hieroglyphs.': '700',
        'The famous Great Sphinx is missing what part?': 'Nose',
        'What did Ancient Egyptians believe made the Nile River overflow every year?': 'The tears of Isis',
        'What is the largest pyramid in Egypt?': 'Pyramid of Khufu',
        'What is the name of the most popular board game developed by Ancient Egyptians?': 'Senet',
        'What type of animal did Ancient Egyptians not typically keep as a pet?': 'Hippo',
        'When did the Ancient Egyptian Empire begin to weaken?': '700 BC',
        'Which empire was the first to conquer the Ancient Egyptians?': 'Assyrian Empire',
        'Which is not considered a phase of the Ancient Egyptian society?': 'Glorious Kingdom',
        'Which of the following was a calendar not followed by the Ancient Egyptians?': 'Animal Calendar',
        'Which of these animals was considered sacred by Ancient Egyptians?': 'Cat',
        'Who is considered to be the first Pharaoh of Egypt?': 'King Menes',
        'Who is considered to be the most important Egyptian god?': 'Ra',
        'Which of the following was not invented by the Ancient Egyptians?': 'Horse saddles'
        },
        {  # Early American History
        '11 Southern states succeeded from the union in 1860 to form the _________ States of America.': 'Confederate',
        'Francis Scott Key wrote which famous piece of American history?': 'The Star Spangled Banner',
        'How long did the Civil War last?': 'Four Years',
        'Most of the original American settlers were from what country?': 'England',
        'President Thomas Jefferson made what large purchase to buy American a lot of new territory?':
                'Louisiana Purchase',
        'The American Revolution was against the ________, the English army.': 'Red Coats',
        'This famous American colony is in modern Massachusetts.': 'Plymouth',
        'This famous display against England\'s taxation threw a luxury item into the sea.': 'Boston Tea Party',
        'What year did the British surrender in the American Revolution?': '1781',
        'What year was the Declaration of Independence signed?': '1776',
        'Where was President Abraham Lincoln assassinated?': 'The Theatre',
        'Which early tax act made American settlers very angry pre-revolution?': 'Stamp Act of 1765',
        'Which natural resource was a large reason many Americans choose to journey westward in the 1800\'s?':'Gold',
        'Which two amendments make up the Reconstruction Acts of 1867 and give African Americans additional freedoms?':
                'Fourteenth and Fifteenth',
        'Who did the United States purchase Alaska from?': 'Russia'
        },
        {  # Famous World Leaders
        'Abraham Lincoln is most famous for _____________.': 'Working to end slavery in America',
        'Akbar created a thriving empire through what modern country?': 'India',
        'Alexander the Great created ____________________.': 'One of the largest empires in the ancient world',
        'Chairman Mao led which government party to victory in China?': 'Communism',
        'Henry VIII wanted to remarry, which contributed to the creation of which religion?': 'The Church of England',
        'Joan of Arc fought bravely for what cause?': 'French Independence',
        'Julius Caesar was key in the expansion of the ___________.': 'Roman Empire',
        'King Henry VIII had how many wives?': 'Six',
        'Mahatma Gandhi devoted his life to what?': 'Indian independence',
        'Napoleon Bonaparte was the famous emperor of _______.': 'France',
        'Nelson Mandela ___________________ before becoming the first President of democratic South Africa in 1994?':
                'spent over 20 years in jail',
        'Thomas Jefferson wrote which famous US document?': 'The Declaration of Independence',
        'What was Julius Caesar\'s motto?': 'I came, I saw, I conquered',
        'Who was Margaret Thatcher?': 'British Prime Minister'
        },
        {  # Greek Mythology Trivia
        'Which Greek god is the god of fertility and wine?': 'Dionysus',
        'Which Greek god is the god of fire and forge?': 'Hephaestus',
        'Which Greek god is the god of flocks and shepherds?': 'Pan',
        'Which Greek god is the god of love?': 'Eros',
        'Which Greek god is the god of music, healing, light and truth?': 'Apollo',
        'Which Greek is the sun titan?': 'Helios',
        'Which Greek god is the god of war?': 'Ares',
        'Which Greek god is the goddess of corn, grain and harvest?': 'Demeter',
        'Which Greek god is the goddess of discord?': 'Eris',
        'Which Greek god is the goddess of intelligence and the arts?': 'Athena',
        'Which Greek god is the goddess of love, desire and beauty?': 'Aphrodite',
        'Which Greek god is the goddess of marriage and childbirth?': 'Hera',
        'Which Greek god is the goddess of springtime?': 'Persephone',
        'Which Greek god is the goddess of youth?': 'Hebe',
        'Which Greek god is the lord of the underworld?': 'Hades',
        'Which Greek god is the personification of death?': 'Thanatos',
        'Which Greek god is the protector of all waters?': 'Poseidon',
        'Which Greek god is the ruler of the Olympian gods?': 'Zeus'
        },
        {  # Norse Mythology Trivia
        'Baldr was the god of what?': 'Beauty, innocence, peace and rebirth',
        'Who was the first Norse god?': 'Buri',
        'Who was the god of dawn?': 'Delling',
        'Who was the god of inspiration?': 'Kvasir',
        'Who was the god of justice, peace and truth?': 'Forseti',
        'Who was the god of revenge?': 'Vali',
        'Who was the god of skiing, winter, hunting and dueling?': 'Ullr',
        'Who was the god of strength and son of Thor?': 'Magni',
        'Who was the god of the daytime?': 'Dagr',
        'Who was the god of war and the "All Father"?': 'Odin',
        'Who was the goddess of consolation and protection?': 'Hlin',
        'Who was the goddess of fertility and plough?': 'Gefjun',
        'Who was the goddess of healing?': 'Eir',
        'Who was the goddess of marriage and motherhood?': 'Frigg',
        'Who was the goddess of prudence?': 'Snotra',
        'Who was the goddess of the sun?': 'Sol',
        'Who was the goddess of wisdom?': 'Vor',
        'Who was the wife of Thor and goddess of the harvest?': 'Sif',
        'Who was the goddess of the sea?': 'Ran',
        'Norse Mythology is the mythology from what group of people?': 'North Germanic',
        'Who was the goddess of spring?': 'Eostre'
        },
        {  # Solar Systems Trivia
        'Every object in our solar system revolves around the _______.': 'Sun',
        'How many planets are in our solar system?': 'Eight',
        'Jupiter has a ________ in its atmosphere but no solid surface.': 'Hurricane',
        'Mars is known as the _____ planet.': 'Red',
        'Saturn is famous for its ________ that rotate around it.': 'Rings',
        'Uranus has a _______ glow to it.': 'Blue',
        'Venus\' atmosphere is primarily made up of what gas?': 'Carbon Dioxide',
        'What are comets made of?': 'Dirty Ice',
        'What is the correct term for Pluto?': 'Dwarf Planet',
        'What is the largest planet in the solar system?': 'Jupiter',
        'What man-made objects exist in our solar system?': 'Satellites & Space Junk',
        'What separates the inner and outer solar system?': 'Band of asteroids',
        'Which is the smallest planet in the solar system?': 'Mercury',
        'Which planet is closest to the sun?': 'Mercury',
        'Which planet is furthest from the sun?': 'Neptune',
        'Which two planets are Earth\'s "neighbors"?': 'Venus & Mars'
        },
        {  # State Nicknames Trivia
        'Which state is known as the "Aloha State?"': 'Hawaii',
        'Which state is known as the "Beaver State?"': 'Oregon',
        'Which state is known as the "Beehive State?"': 'Utah',
        'Which state is known as the "Bluegrass State?"': 'Kentucky',
        'Which state is known as the "Constitution State?"': 'Connecticut',
        'Which state is known as the "Empire State?"': 'New York',
        'Which state is known as the "Evergreen State?"': 'Washington',
        'Which state is known as the "First State?"': 'Delaware',
        'Which state is known as the "Garden State?"': 'New Jersey',
        'Which state is known as the "Golden State?"': 'California',
        'Which state is known as the "Great Lakes State?"': 'Michigan',
        'Which state is known as the "Lone Star State?"': 'Texas',
        'Which state is known as the "Magnolia State?"': 'Mississippi',
        'Which state is known as the "Ocean State?"': 'Rhode Island',
        'Which state is known as the "Pelican State?"': 'Louisiana',
        'Which state is known as the "Pine Tree State?"': 'Maine',
        'Which state is known as the "Prairie State?"': 'Illinois',
        'Which state is known as the "Silver State?"': 'Nevada',
        'Which state is known as the "Sunflower State?"': 'Kansas',
        'Which state is known as the "Volunteer State?"': 'Tennessee'
        },
        {  # Weather Trivia
        'A waterspout is actually a weak ______ that forms over water.': 'Tornado',
        'How fast do raindrops fall?': '7-18 miles per hour',
        'How is snow formed?': 'Water vapor changes directly to ice high in the atmosphere',
        'In which two seasons are thunderstorms most likely to occur?': 'Spring & Summer',
        'The ______ is the center of a hurricane and also the calmest part of the storm.': 'Eye',
        'Tornado are rated on what kind of scale?': 'F Scale',
        'What causes the electric current that result in lightning?': 'Ice particles bumping into each other',
        'What does a Tornado Watch mean?': 'Tornadoes are possible in your area.',
        'What is a monsoon?': 'Seasonal wind that often brings rain',
        'What is a tornado called before it hits the ground?': 'Funnel Cloud',
        'What is sleet?': 'Rain that freezes into ice before it hits ground',
        'What is the name of the strong radar that helps predict weather?': 'Doppler',
        'What type of cloud is above 18,000 feet in the atmosphere?': 'Cirrus',
        'What type of cloud is below 6,500 feet in the atmosphere?': 'Stratus',
        'What type of cloud is between 6,500 feet to 18,000 feet in the atmosphere?': 'Alto',
        'What type of cloud usually looks white and puffy?': 'Cumulus',
        'Where do tornadoes come from?': 'Thunderstorms',
        'Which of the following is not a characteristic of a hurricane?': 'Forms over mountains',
        'Which of the following is NOT needed to cause a blizzard?': 'Rotating storm clouds',
        'Which of these states are not in "Tornado Alley"': 'North Carolina'
        },
        {  # Apollo Missions Trivia
        'In which mission did an astronaut perform a golf shot on the moon?': 'Apollo 14',
        'This Apollo mission never launched and ended in tragedy, when a fire erupted in the command module during'
        ' a test and killed three astronauts.':
                'Apollo 1',
        'Which astronaut was not present on the Apollo 11 mission?': 'Cernan',
        'Which mission cancelled their landing on the moon due to technical problems?': 'Apollo 13',
        'Which mission conducted the first manned flight test of the Lunar Module?': 'Apollo 9',
        'Which mission had a SM oxygen tank explode, which caused many problems?': 'Apollo 13',
        'Which mission had two lightning strikes to the spacecraft during launch?': 'Apollo 12',
        'Which mission provided the first color video images from the surface of the moon?': 'Apollo 14',
        'Which mission broadcasted some of the first live television pictures from space?': 'Apollo 7',
        'Which mission used the Lunar RV for the first time?': 'Apollo 15',
        'Which mission was considered a "dress rehearsal" for a lunar landing?': 'Apollo 10',
        'Which mission was the first manned Apollo flight?': 'Apollo 7',
        'Which mission was the first manned circumlunar flight?': 'Apollo 8',
        'Which mission was the first manned landing on the moon?': 'Apollo 11',
        'Which mission was the first night launch?': 'Apollo 17',
        'Which was the last Apollo mission?': 'Apollo 17'
        },
        {  # World Capitols Trivia
        'What is the capital of Argentina?': 'Buenos Aires',
        'What is the capital of Australia?': 'Canberra',
        'What is the capital of Austria?': 'Vienna',
        'What is the capital of Belgium?': 'Brussels',
        'What is the capital of Brazil?': 'Brasilia',
        'What is the capital of Canada?': 'Ottawa',
        'What is the capital of China?': 'Beijing',
        'What is the capital of Cuba?': 'Havana',
        'What is the capital of Czech Republic?': 'Prague',
        'What is the capital of Denmark?': 'Copenhagen',
        'What is the capital of Egypt?': 'Cairo',
        'What is the capital of Finland?': 'Helsinki',
        'What is the capital of France?': 'Paris',
        'What is the capital of Germany?': 'Berlin',
        'What is the capital of Greece?': 'Athens',
        'What is the capital of Hungary?': 'Budapest',
        'What is the capital of India?': 'New Delhi',
        'What is the capital of Italy?': 'Rome',
        'What is the capital of Japan?': 'Tokyo',
        'What is the capital of Mexico?': 'Mexico City',
        'What is the capital of The Bahamas?': 'Nassau'
    }]
